language:
    - objective-c

before_install:
    - brew update

install:
    - brew install python3
    - brew install cmake

script:
    - export GTEST_DIR=`pwd`

    # Build/install gtest (native platform, if needed):
    - mkdir -p _builds/make
    - cd _builds/make
    - cmake -DCMAKE_INSTALL_PREFIX=${GTEST_DIR}/_install/make ../..
    - make install

    # Build universal(iphone + simulator) iOS library (Xcode only):
    - cd ${GTEST_DIR}
    - mkdir -p _builds/xcode
    - cd _builds/xcode
    - cmake -GXcode -DCMAKE_TOOLCHAIN_FILE=${GTEST_DIR}/cmake/iOS.cmake -DCMAKE_INSTALL_PREFIX=${GTEST_DIR}/_install/ios ../..
    - xcodebuild -target install

    # Check installed iOS libraries (debug + release):
    - lipo -info ${GTEST_DIR}/_install/ios/libgtest.a
    - lipo -info ${GTEST_DIR}/_install/ios/libgtestd.a
