language:
    - objective-c

branches:
  except:
    - master

install:
    - wget https://github.com/ruslo/CMake/archive/ios.universal.tar.gz
    - openssl sha1 ios.universal.tar.gz
    - tar xf ios.universal.tar.gz
    - cmake -HCMake-ios.universal -B_builds/cmake -DCMAKE_USE_SYSTEM_CURL=YES -DCMAKE_BUILD_TYPE=Release
    - cmake --build _builds/cmake --target install

script:
    - which cmake
    - cmake --version

    # Build/install gtest (native platform, if needed):
    - cmake -H. -B_builds/make -DCMAKE_INSTALL_PREFIX="`pwd`/_install/make"
    - cmake --build _builds/make --target install

    # Build universal(iphone + simulator) iOS library (Xcode only):
    - cmake -H. -B_builds/ios -GXcode -DCMAKE_INSTALL_PREFIX="`pwd`/_install/ios" -DCMAKE_TOOLCHAIN_FILE="`pwd`/cmake/iOS.cmake"
    - cmake --build _builds/ios --target install --config Debug
    - cmake --build _builds/ios --target install --config Release

    # Check installed iOS libraries (debug + release):
    - lipo -info "`find _install/ios -name libgtest.a`"
    - lipo -info "`find _install/ios -name libgtestd.a`"
