language:
    - cpp

branches:
  except:
    - master

install:
    - sudo apt-get install cmake
    - sudo apt-get install libcurl3-dev
    - wget https://github.com/ruslo/CMake/archive/ios.universal.tar.gz
    - openssl sha1 ios.universal.tar.gz
    - tar xf ios.universal.tar.gz
    - cmake -HCMake-ios.universal -B_builds/cmake -DCMAKE_USE_SYSTEM_CURL=YES -DCMAKE_BUILD_TYPE=Release
    - cmake --build _builds/cmake
    - sudo cmake --build _builds/cmake --target install
    - export PATH=/usr/local/bin:${PATH}

script:
    - which cmake
    - cmake --version

    # Build/install gtest (native platform, if needed):
    - cmake -H. -B_builds/make -DCMAKE_INSTALL_PREFIX="`pwd`/_install/make"
    - cmake --build _builds/make --target install
